# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b85f3c4eafc1f9bac2d3ccbb41fb09fa56d92dc23157c7ab8fd8c489cb7a965633c31373b156a0649a3e167e9b420154d5554a3a87424331f0def933d7124e7

test:
  secret_key_base: 65cae52e9f13084b39c5c6eaaf078746111115b518bfa319fb23adf88dddda0b2d9cae36c42ce6e07acfe60cc3934807c96afd551a42d3fba7ff67c8b9004fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
